/**
 * The companion setup script, served as a download.
 *
 * Generated rather than read from disk so it works the same whether the API is running from a source
 * checkout or a deployed container, and so the server URL is already correct in the copy the user
 * receives — that URL is the one thing they would otherwise have to know and type.
 */
export function windowsInstallerScript(serverUrl: string): string {
  // Batch has no escaping worth relying on, so keep the interpolated value to a plain URL.
  const safeUrl = serverUrl.replace(/[\r\n"^&|<>%]/g, '');

  return [
    '@echo off',
    'setlocal',
    'title DevFlow companion setup',
    '',
    'rem Installs the DevFlow runtime companion on this machine.',
    'rem The companion detects which AI coding CLIs are installed here. It has to run',
    'rem locally: a browser cannot read your filesystem, and the DevFlow API runs on a',
    'rem server with no view of your computer.',
    '',
    `set "SERVER=${safeUrl}"`,
    'if not "%~1"=="" set "SERVER=%~1"',
    '',
    'echo.',
    'echo   DevFlow companion setup',
    'echo   =======================',
    'echo   Server: %SERVER%',
    'echo.',
    '',
    'where node >nul 2>nul',
    'if errorlevel 1 (',
    '  echo   Node.js is required but was not found on this machine.',
    '  echo   Install Node 20 or newer from https://nodejs.org then run this again.',
    '  echo.',
    '  pause',
    '  exit /b 1',
    ')',
    '',
    'rem Locate the companion source relative to this script.',
    'set "PKG=%~dp0agentic-orchestration-runtime"',
    'if not exist "%PKG%\\package.json" set "PKG=%~dp0..\\agentic-orchestration-runtime"',
    'if not exist "%PKG%\\package.json" (',
    '  echo   Could not find the companion source next to this file.',
    '  echo.',
    '  echo   Move this script into your DevFlow folder - the one containing',
    '  echo   "agentic-orchestration-runtime" - and run it again.',
    '  echo.',
    '  pause',
    '  exit /b 1',
    ')',
    '',
    'echo   Installing from %PKG%',
    'echo.',
    'pushd "%PKG%"',
    'echo   [1/3] Fetching dependencies...',
    'call npm install --no-audit --no-fund >nul 2>nul || goto :fail',
    'echo   [2/3] Building...',
    'call npm run build >nul 2>nul || goto :fail',
    'echo   [3/3] Installing the devflow-runtime command...',
    'call npm install -g . >nul 2>nul || goto :fail',
    'popd',
    '',
    'echo.',
    'echo   Enabling autostart so your CLIs stay visible...',
    'call devflow-runtime service install --server "%SERVER%" || goto :fail',
    '',
    'echo.',
    'echo   ============================================================',
    'echo    Done. Open DevFlow, go to Runtimes, and this machine will',
    'echo    appear on its own - there is nothing to copy or paste.',
    'echo   ============================================================',
    'echo.',
    'pause',
    'exit /b 0',
    '',
    ':fail',
    'popd >nul 2>nul',
    'echo.',
    'echo   Setup did not complete. The messages above should say why.',
    'echo   You can also run these by hand from %PKG%:',
    'echo       npm install',
    'echo       npm run install:global',
    'echo       devflow-runtime service install --server "%SERVER%"',
    'echo.',
    'pause',
    'exit /b 1',
    '',
    // Batch is line-oriented and CRLF-sensitive; joined with \r\n by the caller.
  ].join('\r\n');
}
