import { Injectable, Logger } from '@nestjs/common';
import { RepositoryKind } from '@prisma/client';
import { GithubService } from '../../github/github.service';
import { PrismaService } from '../../prisma/prisma.service';
import { DevFlowStateType } from '../graph/devflow.state';

// ─── Node ─────────────────────────────────────────────────────────────────────

@Injectable()
export class GithubCommitNode {
  private readonly logger = new Logger(GithubCommitNode.name);

  constructor(
    private readonly github: GithubService,
    private readonly prisma: PrismaService,
  ) {}

  /**
   * Delivers one repository's files: onto the run branch behind a pull request when a branch is
   * set, or directly to the default branch for legacy runs checkpointed before branch delivery.
   * Returns the PR url when one was opened.
   */
  private async deliver(
    state: DevFlowStateType,
    repoName: string,
    kind: RepositoryKind,
    files: Array<{ filePath: string; content: string }>,
    commitMessage: string,
    branch: string | null,
  ): Promise<string | null> {
    if (!branch) {
      await this.github.commitFiles(repoName, files, commitMessage);
      this.logger.log(`[${state.projectId}] Committed ${files.length} files to ${repoName} (${kind})`);
      return null;
    }

    await this.github.commitFilesToBranch(repoName, branch, files, commitMessage);

    const body = [
      `Generated by DevFlow orchestration run \`${state.runId}\`.`,
      '',
      `Files in this repository (${kind}):`,
      ...files.map((file) => `- \`${file.filePath}\``),
    ].join('\n');

    const pr = await this.github
      .openPullRequest(repoName, branch, `DevFlow run ${state.runId}: ${state.companyName}`, body)
      .catch((error: unknown) => {
        // A missing PR must not fail delivery — the commit is already safely on the branch.
        this.logger.warn(
          `[${state.projectId}] Could not open PR for ${repoName}: ${error instanceof Error ? error.message : String(error)}`,
        );
        return null;
      });

    const suffix = pr ? ` → ${pr.htmlUrl}` : '';
    this.logger.log(
      `[${state.projectId}] Committed ${files.length} files to ${repoName}@${branch} (${kind})${suffix}`,
    );
    return pr?.htmlUrl ?? null;
  }

  async execute(
    state: DevFlowStateType,
  ): Promise<Partial<DevFlowStateType>> {
    this.logger.log(`[${state.projectId}] Committing artifacts to GitHub`);

    try {
      await this.prisma.project.update({
        where: { id: state.projectId },
        data: { status: 'COMMITTING' },
      });

      const project = await this.prisma.project.findUnique({
        where: { id: state.projectId },
        select: {
          createdById: true,
          groupId: true,
          repoUrl: true,
          repositories: {
            select: { id: true, name: true, htmlUrl: true, cloneUrl: true, status: true, kind: true },
          },
        },
      });
      if (!project) throw new Error(`Project ${state.projectId} not found`);

      // Repos are provisioned deterministically at project creation (with the
      // .gitignore + config + MVVM scaffold). We never create a repo here — the
      // agents only produce feature code, which we route to the matching repo.
      if (project.repositories.length === 0) {
        throw new Error(
          `Project ${state.projectId} has no provisioned repositories; create the project's repositories first.`,
        );
      }
      const repoByKind = new Map(project.repositories.map((repo) => [repo.kind, repo]));

      // Route each artifact to its repo: frontend -> FE, mobile -> MOBILE,
      // everything else (backend/database/architecture/contract) -> BE. Falls
      // back to the backend repo when that kind wasn't provisioned.
      const targetKind = (agentType: string): RepositoryKind => {
        const wanted =
          agentType === 'frontend'
            ? RepositoryKind.FRONTEND
            : agentType === 'mobile'
              ? RepositoryKind.MOBILE
              : RepositoryKind.BACKEND;
        return repoByKind.has(wanted) ? wanted : RepositoryKind.BACKEND;
      };

      const byRepo = new Map<RepositoryKind, typeof state.artifacts>();
      for (const artifact of state.artifacts) {
        const kind = targetKind(artifact.agentType);
        if (!repoByKind.has(kind)) continue;
        const list = byRepo.get(kind) ?? [];
        list.push(artifact);
        byRepo.set(kind, list);
      }

      const commitMessage = `feat: generated code by DevFlow [run:${state.runId}]`;
      // Delivery goes to the run's branch and is reviewed through a pull request; the default
      // branch is never advanced by an agent run. Legacy runs without a branch (checkpoints
      // created before branch delivery existed) still commit directly so they can finish.
      const branch = state.repoBranch?.trim() || null;
      const pullRequests: string[] = [];

      for (const [kind, artifacts] of byRepo) {
        const repo = repoByKind.get(kind)!;
        const files = artifacts.map((a) => ({ filePath: a.filePath, content: a.content }));
        const prUrl = await this.deliver(state, repo.name, kind, files, commitMessage, branch);
        if (prUrl) pullRequests.push(prUrl);
      }

      if (pullRequests.length > 0) {
        this.logger.log(`[${state.projectId}] Opened ${pullRequests.length} pull request(s) for review`);
      }

      const primaryRepo =
        repoByKind.get(RepositoryKind.BACKEND) ?? project.repositories[0];
      const repoUrl = primaryRepo?.htmlUrl ?? primaryRepo?.cloneUrl ?? project.repoUrl;

      // Persist artifacts to DB.
      if (state.artifacts.length > 0) {
        await this.prisma.artifact.createMany({
          data: state.artifacts.map((a) => ({
            projectId: state.projectId,
            agentType: a.agentType,
            filePath: a.filePath,
            content: a.content,
          })),
          skipDuplicates: true,
        });
      }

      // Update project with repository URL.
      await this.prisma.project.update({
        where: { id: state.projectId },
        data: { repoUrl },
      });

      this.logger.log(`[${state.projectId}] GitHub commit complete: ${repoUrl}`);

      return { repoUrl };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      this.logger.error(`[${state.projectId}] GitHub commit failed: ${message}`);

      await this.prisma.project
        .update({
          where: { id: state.projectId },
          data: { status: 'FAILED' },
        })
        .catch(() => undefined);

      return { error: `GithubCommitNode failed: ${message}` };
    }
  }
}
