import { Injectable } from '@nestjs/common';
import { WorkOrderAgentType } from '@prisma/client';
import type { GeneratedWorkOrderOutput, WorkOrderAgentContext } from '../providers/agent-provider.types';
import { normalizeDesignGuidance, type DesignGuidance, type GeneratedArtifact } from '../graph/devflow.state';
import { AGENT_SCHEMAS } from './schemas/artifact-schemas';
import type { ValidationError, ValidationResult } from './schemas/schema.types';
import { checkSyntax } from './syntax-checkers/index';
import { checkTypeScriptProgram } from './syntax-checkers/typescript.program.checker';
import { checkIntegration } from './cross-artifact/integration.checker';
import {
  isDomainContractPath,
  validateDomainContractArtifacts,
  validateDomainContractDrift,
} from '../domain-contracts';

const FORBIDDEN_GENERATED_PATHS = [
  /(^|\/)package(?:-lock)?\.json$/i,
  /(^|\/)pnpm-lock\.yaml$/i,
  /(^|\/)yarn\.lock$/i,
  /(^|\/)tsconfig(?:\.[^/]*)?\.json$/i,
  /(^|\/)next\.config\.(?:js|mjs|ts)$/i,
  /(^|\/)postcss\.config\.(?:js|mjs|ts)$/i,
  /(^|\/)nest-cli\.json$/i,
  /(^|\/)eslint\.config\.(?:js|mjs|ts)$/i,
  /(^|\/)vite\.config\.(?:js|mjs|ts)$/i,
];

const PLACEHOLDER_CONTENT = [
  /\bTODO\b/i,
  /\bFIXME\b/i,
  /implementation goes here/i,
  /\bstub(?:bed)?\b/i,
  /\bplaceholder\b/i,
  /lorem ipsum/i,
  /example\.com/i,
  /not implemented/i,
];

export interface OutputValidationContext {
  designGuidance?: DesignGuidance;
}

@Injectable()
export class OutputValidationService {
  validate(
    output: GeneratedWorkOrderOutput,
    context: WorkOrderAgentContext,
  ): ValidationResult {
    const errors: ValidationError[] = [
      ...this.validateBase(output, context),
      ...this.validateSchema(output, context.workOrder.agentType),
      ...this.validateSyntax(output),
    ];

    return {
      valid: errors.length === 0,
      errors,
      summary: errors.length === 0
        ? `${context.workOrder.agentType} output valid`
        : `${context.workOrder.agentType} output failed: ${errors.map(e => e.message).join('; ')}`,
    };
  }

  validateBatch(
    artifacts: GeneratedArtifact[],
    projectId: string,
    context: OutputValidationContext = {},
  ): ValidationError[] {
    const all: ValidationError[] = [];
    // Files that already failed the single-file parser; the program-level
    // type-check is skipped for these because semantic diagnostics cascade
    // unreliably off a syntax error.
    const filesWithSyntaxErrors = new Set<string>();

    all.push(...this.validateArtifactSet(artifacts));

    for (const artifact of artifacts) {
      const errors = this.validateArtifact(artifact, projectId);
      if (errors.some((e) => e.code === 'TS_SYNTAX')) {
        filesWithSyntaxErrors.add(artifact.filePath);
      }
      all.push(...errors);
    }

    all.push(...this.validateFrontendDesign(artifacts, context.designGuidance));
    all.push(...validateDomainContractArtifacts(artifacts));
    all.push(...this.validateProgram(artifacts, filesWithSyntaxErrors));
    all.push(...this.validateIntegration(artifacts));
    all.push(...validateDomainContractDrift(artifacts));

    return all;
  }

  /**
   * Cross-artifact integration checking: verifies the seams *between* agents —
   * frontend API calls reach a backend route, backend `prisma.<model>` access
   * resolves to a declared schema model. Findings are `CONTRACT` errors
   * attributed to the agent making the unsatisfied reference.
   *
   * Opt-out via `ORCHESTRATION_INTEGRATION_CHECK=false`.
   */
  private validateIntegration(
    artifacts: GeneratedArtifact[],
  ): ValidationError[] {
    if (process.env.ORCHESTRATION_INTEGRATION_CHECK === 'false') return [];
    return checkIntegration(
      artifacts.map((a) => ({
        agentType: a.agentType,
        filePath: a.filePath,
        content: a.content,
      })),
    );
  }

  private validateArtifact(
    artifact: GeneratedArtifact,
    _projectId: string,
  ): ValidationError[] {
    const errors: ValidationError[] = [];
    const filePath = artifact.filePath?.trim() ?? '';

    if (!filePath) {
      errors.push({ code: 'BASE', message: 'Artifact filePath is required' });
    } else if (this.isForbiddenGeneratedPath(filePath)) {
      errors.push({
        code: 'BASE',
        path: filePath,
        message: `Artifact ${filePath} is scaffolded by DevFlow and must not be generated by an agent`,
      });
    }
    if (!artifact.content?.trim() || artifact.content.trim().length < 40) {
      errors.push({ code: 'BASE', message: `Artifact ${artifact.filePath} content must be at least 40 non-empty characters` });
    } else {
      const placeholder = PLACEHOLDER_CONTENT.find((pattern) => pattern.test(artifact.content));
      if (placeholder) {
        errors.push({
          code: 'BASE',
          path: filePath,
          message: `Artifact ${filePath} contains placeholder or stub content matching ${placeholder}`,
        });
      }
    }

    if (!isDomainContractPath(artifact.filePath)) {
      errors.push(...checkSyntax(artifact.content, artifact.filePath));
    }

    // Stamp the owning agent so the validator can route retries precisely.
    return errors.map((e) => ({ agentType: artifact.agentType, ...e }));
  }

  private validateFrontendDesign(
    artifacts: GeneratedArtifact[],
    guidance?: DesignGuidance,
  ): ValidationError[] {
    if (!guidance) return [];

    const normalizedGuidance = normalizeDesignGuidance(guidance);
    const forbiddenPatterns = [
      ...new Set([
        ...normalizedGuidance.forbiddenPatterns,
        ...(normalizedGuidance.designSystem?.antiPatterns ?? []),
      ].map((pattern) => pattern.trim()).filter(Boolean)),
    ];
    const errors: ValidationError[] = [];
    for (const artifact of artifacts) {
      if (artifact.agentType !== 'frontend' || !/\.(tsx|jsx)$/i.test(artifact.filePath)) {
        continue;
      }

      const content = artifact.content;
      const lower = content.toLowerCase();
      const add = (message: string) => {
        errors.push({
          code: 'SCHEMA_VIOLATION',
          path: artifact.filePath,
          message,
          agentType: 'frontend',
        });
      };

      for (const pattern of forbiddenPatterns) {
        const normalized = pattern.trim().toLowerCase();
        if (normalized && lower.includes(normalized)) {
          add(`Frontend artifact uses forbidden design pattern/anti-pattern "${pattern}" from the PM design contract`);
        }
      }

      if (/<(?:input|select|textarea)\b/i.test(content) && !/<label\b/i.test(content) && !/aria-(?:label|labelledby)=/i.test(content)) {
        add('Frontend form controls need visible labels or aria-label/aria-labelledby attributes');
      }

      if (/<img\b/i.test(content) && !/<img\b[^>]*\balt=/i.test(content)) {
        add('Frontend images need alt text');
      }

      const fetchesData = /\b(fetch|axios|useQuery|useSWR)\b/i.test(content);
      if (fetchesData && !/\bloading\b/i.test(content)) {
        add('Frontend data-fetching UI needs a loading state');
      }
      if (fetchesData && !/\b(error|failed|failure)\b/i.test(content)) {
        add('Frontend data-fetching UI needs an error state');
      }
      if (fetchesData && !/\b(empty|no\s+\w+|length\s*===\s*0)\b/i.test(content)) {
        add('Frontend data-fetching UI needs an empty state');
      }

      const nonSemanticClick = /<(?:div|span|section|article|li|tr|td)\b(?=[^>]*onClick=)(?![^>]*\brole=)(?![^>]*\btabIndex=)/i.test(content);
      if (normalizedGuidance.accessibilityLevel === 'strict' && nonSemanticClick) {
        add('Strict accessibility requires non-semantic clickable elements to include role and keyboard focus handling');
      }
    }

    return errors;
  }

  private validateArtifactSet(artifacts: GeneratedArtifact[]): ValidationError[] {
    const errors: ValidationError[] = [];
    const seen = new Map<string, GeneratedArtifact>();

    for (const artifact of artifacts) {
      const filePath = artifact.filePath?.trim();
      if (!filePath) continue;

      const first = seen.get(filePath);
      if (first) {
        errors.push({
          code: 'BASE',
          path: filePath,
          message: `Duplicate generated filePath: ${filePath}`,
          agentType: artifact.agentType,
        });
        if (first.agentType !== artifact.agentType) {
          errors.push({
            code: 'BASE',
            path: filePath,
            message: `Duplicate generated filePath already owned by ${first.agentType}: ${filePath}`,
            agentType: first.agentType,
          });
        }
      } else {
        seen.set(filePath, artifact);
      }
    }

    return errors;
  }

  /**
   * Type-aware cross-file checking: builds a `ts.Program` over the whole
   * artifact set and reports the high-signal "references something that does
   * not exist" diagnostics the single-file parser cannot see. Each error is
   * attributed back to the agent that owns the offending file.
   *
   * Opt-out via `ORCHESTRATION_TYPECHECK=false` if it proves noisy in a given
   * environment.
   */
  private validateProgram(
    artifacts: GeneratedArtifact[],
    skipPaths: Set<string>,
  ): ValidationError[] {
    if (process.env.ORCHESTRATION_TYPECHECK === 'false') return [];

    const agentByPath = new Map(artifacts.map((a) => [a.filePath, a.agentType]));
    const programErrors = checkTypeScriptProgram(
      artifacts.map((a) => ({ filePath: a.filePath, content: a.content })),
    );

    const out: ValidationError[] = [];
    for (const [filePath, errors] of programErrors) {
      if (skipPaths.has(filePath)) continue;
      for (const error of errors) {
        out.push({ ...error, agentType: agentByPath.get(filePath) });
      }
    }
    return out;
  }

  private validateBase(
    output: GeneratedWorkOrderOutput,
    context: WorkOrderAgentContext,
  ): ValidationError[] {
    const errors: ValidationError[] = [];
    const expectedPrefix = `work-orders/${context.workOrder.id}/`;

    if (!output.filePath?.trim()) {
      errors.push({ code: 'BASE', message: 'filePath is required' });
    } else if (!output.filePath.startsWith(expectedPrefix)) {
      errors.push({ code: 'BASE', message: `filePath must start with ${expectedPrefix}` });
    } else if (this.isForbiddenGeneratedPath(output.filePath)) {
      errors.push({ code: 'BASE', path: output.filePath, message: `${output.filePath} is scaffolded by DevFlow and must not be generated by an agent` });
    }

    if (!output.displayName?.trim()) {
      errors.push({ code: 'BASE', message: 'displayName is required' });
    }

    if (!output.content?.trim() || output.content.trim().length < 40) {
      errors.push({ code: 'BASE', message: 'content must be at least 40 non-empty characters' });
    } else {
      const placeholder = PLACEHOLDER_CONTENT.find((pattern) => pattern.test(output.content));
      if (placeholder) {
        errors.push({ code: 'BASE', path: output.filePath, message: `content contains placeholder or stub text matching ${placeholder}` });
      }
    }

    return errors;
  }

  private isForbiddenGeneratedPath(filePath: string): boolean {
    return FORBIDDEN_GENERATED_PATHS.some((pattern) => pattern.test(filePath.replace(/\\/g, '/')));
  }

  private validateSchema(
    output: GeneratedWorkOrderOutput,
    agentType: WorkOrderAgentType,
  ): ValidationError[] {
    const schema = AGENT_SCHEMAS[agentType];
    const result = schema.safeParse({
      filePath: output.filePath,
      content: output.content,
    });

    if (result.success) return [];

    return result.error.issues.map(issue => ({
      code: 'SCHEMA_VIOLATION' as const,
      path: issue.path.join('.'),
      message: issue.message,
    }));
  }

  private validateSyntax(output: GeneratedWorkOrderOutput): ValidationError[] {
    return checkSyntax(output.content, output.filePath);
  }
}
